"""initial schema

Revision ID: 3089f7bc722b
Revises: 
Create Date: 2026-07-05 16:43:10.893658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3089f7bc722b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('num_steps', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_fetched_at'), 'agent_runs', ['fetched_at'], unique=False)
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('factor_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('methodology_tag', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_user_session_created', 'chat_messages', ['user_id', 'session_id', 'created_at'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('attendees', sa.Integer(), nullable=True),
    sa.Column('event_days', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('travel_tco2e', sa.Float(), nullable=True),
    sa.Column('venue_energy_tco2e', sa.Float(), nullable=True),
    sa.Column('accommodation_tco2e', sa.Float(), nullable=True),
    sa.Column('catering_tco2e', sa.Float(), nullable=True),
    sa.Column('materials_waste_tco2e', sa.Float(), nullable=True),
    sa.Column('equipment_tco2e', sa.Float(), nullable=True),
    sa.Column('swag_tco2e', sa.Float(), nullable=True),
    sa.Column('digital_tco2e', sa.Float(), nullable=True),
    sa.Column('total_tco2e', sa.Float(), nullable=True),
    sa.Column('per_attendee_tco2e', sa.Float(), nullable=True),
    sa.Column('data_quality', sa.String(), nullable=True),
    sa.Column('scope1_tco2e', sa.Float(), nullable=True),
    sa.Column('scope2_tco2e', sa.Float(), nullable=True),
    sa.Column('scope3_tco2e', sa.Float(), nullable=True),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('factors_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenarios_user_created', 'scenarios', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('baseline_tco2e', sa.Float(), nullable=True),
    sa.Column('reduced_tco2e', sa.Float(), nullable=True),
    sa.Column('total_savings_usd', sa.Float(), nullable=True),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reports_created_at'), 'financial_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_financial_reports_scenario_id'), 'financial_reports', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_financial_reports_user_id'), 'financial_reports', ['user_id'], unique=False)
    op.create_index('ix_financial_reports_user_scenario_created', 'financial_reports', ['user_id', 'scenario_id', 'created_at'], unique=False)
    op.create_table('offset_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('registry', sa.String(), nullable=False),
    sa.Column('quantity_tco2e', sa.Float(), nullable=False),
    sa.Column('price_per_tco2e_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offset_purchases_created_at'), 'offset_purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_offset_purchases_scenario_id'), 'offset_purchases', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_offset_purchases_status'), 'offset_purchases', ['status'], unique=False)
    op.create_index('ix_offset_purchases_user_created', 'offset_purchases', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_offset_purchases_user_id'), 'offset_purchases', ['user_id'], unique=False)
    op.create_index('ix_offset_purchases_user_scenario_status', 'offset_purchases', ['user_id', 'scenario_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offset_purchases_user_scenario_status', table_name='offset_purchases')
    op.drop_index(op.f('ix_offset_purchases_user_id'), table_name='offset_purchases')
    op.drop_index('ix_offset_purchases_user_created', table_name='offset_purchases')
    op.drop_index(op.f('ix_offset_purchases_status'), table_name='offset_purchases')
    op.drop_index(op.f('ix_offset_purchases_scenario_id'), table_name='offset_purchases')
    op.drop_index(op.f('ix_offset_purchases_created_at'), table_name='offset_purchases')
    op.drop_table('offset_purchases')
    op.drop_index('ix_financial_reports_user_scenario_created', table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_user_id'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_scenario_id'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_created_at'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_index('ix_scenarios_user_created', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('ix_chat_messages_user_session_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_agent_runs_fetched_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
