"""immutable report snapshots (report_snapshots) + Data-API lockdown for it

Adds the append-only table that stores every exported report package verbatim,
with the factor-catalog version, engine version, and a sha256 of the canonical
payload JSON so a delivered report can be verified later.

Hand-written (not autogenerated). Applies the same posture as every other table:
RLS enabled, anon/authenticated grants revoked, and a permissive FOR ALL policy
plus DML grants for the least-privilege runtime role — see a1b2c3d4e5f6 /
b2c3d4e5f6a7 and app/models/db_security.py.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-08-29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.db_security import lock_down_tables

# revision identifiers, used by Alembic.
revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, None] = "c3d4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = "report_snapshots"
_APP_ROLE = "cutcarbon_app"


def upgrade() -> None:
    op.create_table(
        _TABLE,
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("ef_version", sa.String(), nullable=False),
        sa.Column("engine_version", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        # SET NULL, not CASCADE: deleting the working scenario must not erase the
        # audit trail of what was already reported.
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_snapshots_user_id"), _TABLE, ["user_id"], unique=False)
    op.create_index(op.f("ix_report_snapshots_scenario_id"), _TABLE, ["scenario_id"], unique=False)
    op.create_index(op.f("ix_report_snapshots_created_at"), _TABLE, ["created_at"], unique=False)
    op.create_index(op.f("ix_report_snapshots_sha256"), _TABLE, ["sha256"], unique=False)
    op.create_index(
        "ix_report_snapshots_user_scenario_created",
        _TABLE,
        ["user_id", "scenario_id", "created_at"],
        unique=False,
    )

    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return  # sqlite dev fallback has no PostgREST / anon roles

    # Data-API lockdown: RLS on, anon/authenticated grants revoked.
    lock_down_tables(bind, [_TABLE], "public")

    # Least-privilege runtime role: DML only, allowed through RLS by a permissive
    # policy. Ownership is still enforced in Python (see app/routers/exports.py).
    # Skipped on a bare Postgres where b2c3d4e5f6a7 never created the role.
    role_exists = bind.execute(
        sa.text("SELECT 1 FROM pg_roles WHERE rolname = :role"), {"role": _APP_ROLE}
    ).scalar()
    if role_exists:
        q = f'"public"."{_TABLE}"'
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {q} TO {_APP_ROLE}")
        op.execute(f"DROP POLICY IF EXISTS app_all ON {q}")
        op.execute(f"CREATE POLICY app_all ON {q} FOR ALL TO {_APP_ROLE} USING (true) WITH CHECK (true)")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute(f'DROP POLICY IF EXISTS app_all ON "public"."{_TABLE}"')
    op.drop_index("ix_report_snapshots_user_scenario_created", table_name=_TABLE)
    op.drop_index(op.f("ix_report_snapshots_sha256"), table_name=_TABLE)
    op.drop_index(op.f("ix_report_snapshots_created_at"), table_name=_TABLE)
    op.drop_index(op.f("ix_report_snapshots_scenario_id"), table_name=_TABLE)
    op.drop_index(op.f("ix_report_snapshots_user_id"), table_name=_TABLE)
    op.drop_table(_TABLE)
